"""empty message

Revision ID: 0121eb59d1f8
Revises: 2f1976ce8ba6
Create Date: 2020-06-15 19:13:12.343433

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0121eb59d1f8'
down_revision = '2f1976ce8ba6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('image_name', sa.String(length=128), nullable=False))
    op.drop_column('image', 'imagename')
    op.add_column('label', sa.Column('label_name', sa.String(length=128), nullable=False))
    op.drop_column('label', 'labelname')
    op.add_column('project', sa.Column('project_description', sa.String(length=128), nullable=True))
    op.add_column('project', sa.Column('project_name', sa.String(length=80), nullable=False))
    op.drop_column('project', 'projectname')
    op.drop_column('project', 'projectdescription')
    op.add_column('team', sa.Column('team_name', sa.String(length=80), nullable=False))
    op.drop_column('team', 'teamname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('teamname', mysql.VARCHAR(length=80), nullable=False))
    op.drop_column('team', 'team_name')
    op.add_column('project', sa.Column('projectdescription', mysql.VARCHAR(length=128), nullable=True))
    op.add_column('project', sa.Column('projectname', mysql.VARCHAR(length=80), nullable=False))
    op.drop_column('project', 'project_name')
    op.drop_column('project', 'project_description')
    op.add_column('label', sa.Column('labelname', mysql.VARCHAR(length=128), nullable=False))
    op.drop_column('label', 'label_name')
    op.add_column('image', sa.Column('imagename', mysql.VARCHAR(length=128), nullable=False))
    op.drop_column('image', 'image_name')
    # ### end Alembic commands ###
