"""empty message

Revision ID: 31d3e32516c0
Revises: 7abdf79c4c76
Create Date: 2020-05-26 13:27:36.712781

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '31d3e32516c0'
down_revision = '7abdf79c4c76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'projectmember_ibfk_1', 'projectmember', type_='foreignkey')
    op.drop_column('projectmember', 'project_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projectmember', sa.Column('project_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key(u'projectmember_ibfk_1', 'projectmember', 'project', ['project_id'], ['id'])
    # ### end Alembic commands ###
