"""empty message

Revision ID: efd753d43546
Revises: bc4b203abbd8
Create Date: 2020-06-11 22:39:34.531141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efd753d43546'
down_revision = 'bc4b203abbd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('type', sa.String(length=45), nullable=False),
    sa.Column('source', sa.String(length=45), nullable=False),
    sa.Column('preprocessing_steps_jon_url', sa.String(length=45), nullable=True),
    sa.Column('layers_jon_url', sa.String(length=45), nullable=True),
    sa.Column('train', sa.Float(precision=4, asdecimal=2), nullable=True),
    sa.Column('test', sa.Float(precision=4, asdecimal=2), nullable=True),
    sa.Column('validation', sa.Float(precision=4, asdecimal=2), nullable=True),
    sa.Column('epochs', sa.Integer(), nullable=True),
    sa.Column('batch_size', sa.Integer(), nullable=True),
    sa.Column('learning_rate', sa.Float(precision=4, asdecimal=2), nullable=True),
    sa.Column('loss', sa.String(length=45), nullable=True),
    sa.Column('optimizer', sa.String(length=45), nullable=True),
    sa.Column('metric', sa.String(length=45), nullable=True),
    sa.Column('loss_graph_url', sa.String(length=45), nullable=True),
    sa.Column('accuracy_graph_url', sa.String(length=45), nullable=True),
    sa.Column('saved_model_url', sa.String(length=45), nullable=True),
    sa.Column('transfer_source', sa.String(length=45), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('model')
    # ### end Alembic commands ###
