export const INITIALIZE_PROJECT_REQUEST = 'INITIALIZE_PROJECT_REQUEST',
  INITIALIZE_PROJECT_SUCCESS = 'INITIALIZE_PROJECT_SUCCESS',
  INITIALIZE_PROJECT_FAILURE = 'INITIALIZE_PROJECT_FAILURE',
  UPDATE_PROJECT_REQUEST = 'UPDATE_PROJECT_REQUEST',
  UPDATE_PROJECT_SUCCESS = 'UPDATE_PROJECT_SUCCESS',
  UPDATE_PROJECT_FAILURE = 'UPDATE_PROJECT_FAILURE'
