export const POST_IMAGE_REQUEST = "POST_IMAGE_REQUEST",
  POST_IMAGE_SUCCESS = "POST_IMAGE_SUCCESS",
  POST_IMAGE_FAILURE = "POST_IMAGE_FAILURE",
  FETCH_IMAGE_FAILURE = "FETCH_IMAGE_FAILURE",
  FETCH_IMAGE_REQUEST = "FETCH_IMAGE_REQUEST",
  FETCH_IMAGE_SUCCESS = "FETCH_IMAGE_SUCCESS";
