export const POST_IMAGE_REQUEST = "POST_IMAGE_REQUEST",
  POST_IMAGE_SUCCESS = "POST_IMAGE_SUCCESS",
  POST_IMAGE_FAILURE = "POST_IMAGE_FAILURE",
  IMAGE_PREVIEW_REQUEST = "IMAGE_PREVIEW_REQUEST",
  IMAGE_PREVIEW_SUCCESS = "IMAGE_PREVIEW_SUCCESS";
