export const POST_LABEL_REQUEST = "POST_LABEL_REQUEST",
  POST_LABEL_SUCCESS = "POST_LABEL_SUCCESS",
  POST_LABEL_FAILURE = "POST_LABEL_FAILURE",
  CREATE_LABEL_REQUEST = "CREATE_LABEL_REQUEST",
  CREATE_LABEL_SUCCESS = "CREATE_LABEL_SUCCESS",
  CREATE_LABEL_FAILURE = "CREATE_LABEL_FAILURE";
