export const ADD_LABEL = 'ADD_LABEL',
  REMOVE_LABEL = 'REMOVE_LABEL',
  ADD_PREPROCESSING_STEP = 'ADD_PREPROCESSING_STEP',
  REMOVE_PREPROCESSING_STEP = 'REMOVE_PREPROCESSING_STEP',
  SET_TRAIN_TEST_SPLIT = 'SET_TRAIN_TEST_SPLIT'
