export const FETCH_NOTIFICATION_REQUEST = 'FETCH_NOTIFICATION_REQUEST',
FETCH_NOTIFICATION_SUCCESS = 'FETCH_NOTIFICATION_SUCCESS',
FETCH_NOTIFICATION_FAILURE = 'FETCH_NOTIFICATION_FAILURE',
REMOVE_TOAST_NOTIFICATION = 'REMOVE_TOAST_NOTIFICATION',
RECEIVE_NOTIFICATION = 'RECEIVE_NOTIFICATION'
