-- MySQL Script generated by MySQL Workbench
-- Wed May 20 21:13:13 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema labellab
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema labellab
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `labellab` DEFAULT CHARACTER SET latin1 ;
USE `labellab` ;

-- -----------------------------------------------------
-- Table `labellab`.`alembic_version`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `labellab`.`alembic_version` (
  `version_num` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`version_num`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `labellab`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `labellab`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(80) NOT NULL,
  `username` VARCHAR(80) NOT NULL,
  `password` VARCHAR(128) NULL DEFAULT NULL,
  `email` VARCHAR(100) NOT NULL,
  `date` DATETIME NULL DEFAULT NULL,
  `thumbnail` VARCHAR(1500) NULL DEFAULT NULL,
  `projects` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE,
  UNIQUE INDEX `username` (`username` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `labellab`.`project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `labellab`.`project` (
  `id` INT NOT NULL,
  `project_name` VARCHAR(45) NULL,
  `project_description` VARCHAR(150) NULL,
  `user_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_project_user_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_project_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `labellab`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `labellab`.`versions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `labellab`.`versions` (
  `id` INT NOT NULL,
  `result_id` INT NOT NULL,
  `project_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_versions_project1_idx` (`project_id` ASC) VISIBLE,
  CONSTRAINT `fk_versions_project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `labellab`.`project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `labellab`.`images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `labellab`.`images` (
  `id` INT NOT NULL,
  `image_name` VARCHAR(45) NOT NULL,
  `imageurl` VARCHAR(45) NOT NULL,
  `height` VARCHAR(45) NULL,
  `width` VARCHAR(45) NULL,
  `labelled` TINYINT NOT NULL DEFAULT 0,
  `labeldata` JSON NULL,
  `project_id` INT NOT NULL,
  `versions_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_images_project1_idx` (`project_id` ASC) VISIBLE,
  INDEX `fk_images_versions1_idx` (`versions_id` ASC) VISIBLE,
  CONSTRAINT `fk_images_project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `labellab`.`project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_images_versions1`
    FOREIGN KEY (`versions_id`)
    REFERENCES `labellab`.`versions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `labellab`.`labels`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `labellab`.`labels` (
  `id` VARCHAR(45) NOT NULL,
  `label_name` VARCHAR(45) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `count` INT NOT NULL DEFAULT 0,
  `project_id` INT NOT NULL,
  `images_id` INT NOT NULL,
  INDEX `fk_labels_project1_idx` (`project_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  INDEX `fk_labels_images1_idx` (`images_id` ASC) VISIBLE,
  CONSTRAINT `fk_labels_project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `labellab`.`project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_labels_images1`
    FOREIGN KEY (`images_id`)
    REFERENCES `labellab`.`images` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `labellab`.`teams`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `labellab`.`teams` (
  `id` INT NOT NULL,
  `roles` VARCHAR(45) NULL,
  `team_name` VARCHAR(45) NOT NULL,
  `project_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_teams_project1_idx` (`project_id` ASC) VISIBLE,
  CONSTRAINT `fk_teams_project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `labellab`.`project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `labellab`.`project_members`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `labellab`.`project_members` (
  `user_id` INT NOT NULL,
  `project_id` INT NOT NULL,
  `team_id` INT NULL,
  INDEX `fk_project members_project1_idx` (`project_id` ASC) VISIBLE,
  PRIMARY KEY (`user_id`, `project_id`),
  INDEX `fk_project members_teams1_idx` (`team_id` ASC) VISIBLE,
  CONSTRAINT `fk_project members_project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `labellab`.`project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_project members_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `labellab`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_project members_teams1`
    FOREIGN KEY (`team_id`)
    REFERENCES `labellab`.`teams` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `labellab`.`locations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `labellab`.`locations` (
  `id` INT NOT NULL,
  `date` DATETIME NOT NULL,
  `longitude` DOUBLE NOT NULL,
  `latitude` DOUBLE NOT NULL,
  `images_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_locations_images1_idx` (`images_id` ASC) VISIBLE,
  CONSTRAINT `fk_locations_images1`
    FOREIGN KEY (`images_id`)
    REFERENCES `labellab`.`images` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
