-- MySQL Script generated by MySQL Workbench
-- Fri Jun  5 07:26:37 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema labellab
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema labellab
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `labellab` DEFAULT CHARACTER SET latin1 ;
USE `labellab` ;

-- -----------------------------------------------------
-- Table `labellab`.`alembic_version`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `labellab`.`alembic_version` ;

CREATE TABLE IF NOT EXISTS `labellab`.`alembic_version` (
  `version_num` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`version_num`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `labellab`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `labellab`.`user` ;

CREATE TABLE IF NOT EXISTS `labellab`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(80) NOT NULL,
  `username` VARCHAR(80) NOT NULL,
  `password` VARCHAR(128) NULL DEFAULT NULL,
  `email` VARCHAR(100) NOT NULL,
  `date` DATETIME NULL DEFAULT NULL,
  `thumbnail` VARCHAR(1500) NULL DEFAULT NULL,
  `projects` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email` (`email` ASC),
  UNIQUE INDEX `username` (`username` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `labellab`.`project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `labellab`.`project` ;

CREATE TABLE IF NOT EXISTS `labellab`.`project` (
  `id` INT NOT NULL,
  `project_name` VARCHAR(45) NULL,
  `project_description` VARCHAR(150) NULL,
  `admin_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_project_user_idx` (`admin_id` ASC),
  CONSTRAINT `fk_project_user`
    FOREIGN KEY (`admin_id`)
    REFERENCES `labellab`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `labellab`.`image`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `labellab`.`image` ;

CREATE TABLE IF NOT EXISTS `labellab`.`image` (
  `id` INT NOT NULL,
  `image_name` VARCHAR(45) NOT NULL,
  `imageurl` VARCHAR(45) NOT NULL,
  `height` VARCHAR(45) NULL,
  `width` VARCHAR(45) NULL,
  `labelled` TINYINT NOT NULL DEFAULT 0,
  `date` DATETIME NULL,
  `latitude` DOUBLE NULL,
  `longitude` DOUBLE NULL,
  `project_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_images_project1_idx` (`project_id` ASC),
  CONSTRAINT `fk_images_project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `labellab`.`project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `labellab`.`label`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `labellab`.`label` ;

CREATE TABLE IF NOT EXISTS `labellab`.`label` (
  `id` VARCHAR(45) NOT NULL,
  `label_name` VARCHAR(45) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `count` INT NOT NULL DEFAULT 0,
  `project_id` INT NOT NULL,
  INDEX `fk_labels_project1_idx` (`project_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_labels_project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `labellab`.`project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `labellab`.`team`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `labellab`.`team` ;

CREATE TABLE IF NOT EXISTS `labellab`.`team` (
  `id` INT NOT NULL,
  `roles` VARCHAR(45) NULL,
  `team_name` VARCHAR(45) NOT NULL,
  `project_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_teams_project1_idx` (`project_id` ASC),
  CONSTRAINT `fk_teams_project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `labellab`.`project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `labellab`.`project_member`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `labellab`.`project_member` ;

CREATE TABLE IF NOT EXISTS `labellab`.`project_member` (
  `user_id` INT NOT NULL,
  `team_id` INT NULL,
  PRIMARY KEY (`user_id`),
  INDEX `fk_project members_teams1_idx` (`team_id` ASC),
  CONSTRAINT `fk_project members_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `labellab`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_project members_teams1`
    FOREIGN KEY (`team_id`)
    REFERENCES `labellab`.`team` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `labellab`.`label_data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `labellab`.`label_data` ;

CREATE TABLE IF NOT EXISTS `labellab`.`label_data` (
  `id` INT NOT NULL,
  `months_passed` INT NULL,
  `image_id` INT NOT NULL,
  `label_id` INT NOT NULL,
  `latitude` INT NULL,
  `longitude` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_label_data_image1_idx` (`image_id` ASC),
  INDEX `fk_label_data_label1_idx` (`label_id` ASC),
  CONSTRAINT `fk_label_data_image1`
    FOREIGN KEY (`image_id`)
    REFERENCES `labellab`.`image` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_label_data_label1`
    FOREIGN KEY (`label_id`)
    REFERENCES `labellab`.`label` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `labellab`.`image_has_label`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `labellab`.`image_has_label` ;

CREATE TABLE IF NOT EXISTS `labellab`.`image_has_label` (
  `image_id` INT NOT NULL,
  `label_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`image_id`, `label_id`),
  INDEX `fk_image_has_label_label1_idx` (`label_id` ASC),
  INDEX `fk_image_has_label_image1_idx` (`image_id` ASC),
  CONSTRAINT `fk_image_has_label_image1`
    FOREIGN KEY (`image_id`)
    REFERENCES `labellab`.`image` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_image_has_label_label1`
    FOREIGN KEY (`label_id`)
    REFERENCES `labellab`.`label` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `labellab`.`group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `labellab`.`group` ;

CREATE TABLE IF NOT EXISTS `labellab`.`group` (
  `id` INT NOT NULL,
  `group_name` VARCHAR(45) NULL,
  `project_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_group_project1_idx` (`project_id` ASC),
  CONSTRAINT `fk_group_project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `labellab`.`project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `labellab`.`group_has_image`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `labellab`.`group_has_image` ;

CREATE TABLE IF NOT EXISTS `labellab`.`group_has_image` (
  `group_id` INT NOT NULL,
  `image_id` INT NOT NULL,
  INDEX `fk_group_has_image_group1_idx` (`group_id` ASC),
  INDEX `fk_group_has_image_image1_idx` (`image_id` ASC),
  CONSTRAINT `fk_group_has_image_group1`
    FOREIGN KEY (`group_id`)
    REFERENCES `labellab`.`group` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_group_has_image_image1`
    FOREIGN KEY (`image_id`)
    REFERENCES `labellab`.`image` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
